import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="p-[1.4rem] bg-[blue] text-[white] text-[1.5rem] text-center">
          header component
        </header>
        {children}
        <footer className="p-[1.4rem] bg-[green] text-[white] text-[1.7rem] text-center">
          footer component
        </footer>
      </body>
    </html>
  );
}
