"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: {
//     default: "NextJS 15 tutorial - CodingRobin",
//     template: "%s | CodingRobin",
//     absolute: "",
//   },
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [value, setValue] = useState("")

  const navLinks = [
    { name: "register", href: "/register" },
    { name: "login", href: "/login" },
    { name: "forgotPassword", href: "/forgotPassword" },
  ]

  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="header gap-7 p-[1.4rem] bg-[blue] text-[white] text-[1.5rem] text-center">
          {
            navLinks.map((element, index) => {
              const activeLink =
                pathname == element.href || (pathname.startsWith(element.href) && element.href != "/")
              return (
                <Link
                  key={index}
                  className={activeLink ? "font-bold" : ""}
                  href={element.href}
                >
                  <li>{element.name}</li>
                </Link>
              )
            })
          }
        </header>
        <input type="text" value={value} onChange={e => setValue(e.target.value)} />
        {/* <span>textValue: {value}</span> */}
        <ErrorWrapper>
          {children}
        </ErrorWrapper>
        <footer className="p-[1.4rem] bg-[green] text-[white] text-[1.7rem] text-center">
          footer component
        </footer>
      </body>
    </html>
  );
}
